<a href="https://colab.research.google.com/github/EnesKcuk/MachineLearning/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np 
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)


[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [8]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)



[[ 6  5]
 [11  7]
 [ 4  8]]


In [9]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)



[ 5  6  7  8  9 10 11]


In [14]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)


[72 71 76 54 93 62]


In [15]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 


[0.98323164 0.31883352 0.48822786 0.91031554 0.82230131 0.07998517]


In [13]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.49465574 2.50413545 2.58095595 2.98742335 2.13243151 2.92146578]


In [16]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)


[216 213 228 162 279 186]


In [17]:
feature = np.arange(6,21)
print(feature)
label = (feature * 3) + 4
print(label)



[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [18]:
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise 
print(label)

[-1.16472505 -1.64997322  1.01992279  0.07506043 -1.48129983  1.42707116
 -1.90582393 -0.17898594 -1.5220691   1.25133998  0.28420142  1.85385523
 -1.81661716  0.76431262  1.75725504]
[20.83527495 23.35002678 29.01992279 31.07506043 32.51870017 38.42707116
 38.09417607 42.82101406 44.4779309  50.25133998 52.28420142 56.85385523
 56.18338284 61.76431262 65.75725504]
